language: python
python:
  - "2.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_d75a286f8cf7_key -iv $encrypted_d75a286f8cf7_iv -in creds.py.enc -out tests/_credentials.py -d


# command to install dependencies
install: 
  - pip install .
# command to run tests
script: py.test
